name: Linux Release
permissions:
  contents: write

on:
  push:
    branches: [ yanquan2020-patch-1 ]
  pull_request:
    branches: [ yanquan2020-patch-1 ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.4'
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools
          sudo wget https://musl.cc/arm-linux-musleabi-cross.tgz
          tar xzf arm-linux-musleabi-cross.tgz
          sudo mv arm-linux-musleabi-cross /opt/
          export PATH=/opt/arm-linux-musleabi-cross/bin:$PATH
          CC=arm-linux-musleabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -ldflags "-s -w -X 'go-file/common.Version=v0.4.12' -extldflags '-static'" -o ./go-file-arm   
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: go-file-arm
          path: $GITHUB_WORKSPACE/script/.
