name: Linux Release
permissions:
  contents: write

on:
  push:
    branches: [ yanquan2020-patch-1 ]
  pull_request:
    branches: [ yanquan2020-patch-1 ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.4'
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf
          CC=arm-linux-gnueabihf-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -ldflags "-s -w -X 'go-file/common.Version=$(git describe --tags)' -extldflags '-static'" -o ./go-file-arm
